name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run E2E tests
        uses: cypress-io/github-action@v4
        with:
          start: "npm run start:ci"
          wait-on: "http://localhost:8888"
          # let's see if the Test Runner handles url in the config
          # https://github.com/cypress-io/cypress/issues/5466
          config: baseUrl=http://localhost:8888
      - name: 'Upload screenshots and videos to Slack'
        uses: trymbill/cypress-slack-video-upload-action@v1.3.0
        if: failure()
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channels: 'engineering-ops'
          message-text: 'Cypress tests failed! They have been placed in this thread, good luck.'
          workdir: 'test/cypress'

      
